
const SAMPLE = `def calculate_total(items):\n    total = 0\n    for item in items:\n        if item is None:\n            continue\n        total += item.price\n    return total\n\nprint(calculate_total([]))\n`;
const state = {files:new Map(),active:null,editor:null,monaco:null,aiResult:null,lastOutput:null,history:[],running:false,timer:null,debounce:900,theme:'dark',abort:null,detected:null};
const $=id=>document.getElementById(id);
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const LANGS={py:'python',js:'javascript',mjs:'javascript',cjs:'javascript',ts:'typescript',tsx:'typescript',jsx:'javascript',java:'java',c:'c',cc:'cpp',cpp:'cpp',cxx:'cpp',cs:'csharp',go:'go',rs:'rust',php:'php',rb:'ruby',swift:'swift',kt:'kotlin',kts:'kotlin',html:'html',css:'css',json:'json',sql:'sql',md:'markdown',yaml:'yaml',yml:'yaml'};
function languageFor(name){return LANGS[(name.split('.').pop()||'').toLowerCase()]||'plaintext';}
function current(){return state.active?state.files.get(state.active):null;}
function setStatus(text,kind='ready'){$('statusText').textContent=text;$('statusLight').className='status-ready '+kind;}
function renderTabs(){$('fileTabs').innerHTML=[...state.files.values()].map(f=>`<button class="file-tab ${f.name===state.active?'active':''}" data-file="${esc(f.name)}"><span class="file-icon">${esc(f.language)}</span>${esc(f.name)}${f.dirty?'<span class="dirty">●</span>':''}<span class="tab-x" data-close-file="${esc(f.name)}">×</span></button>`).join('');}
function renderContext(){const f=current();$('aiContext').textContent=f?`${f.name} · ${f.language}${state.detected?.framework?' · '+state.detected.framework:''}`:'No file selected';$('fileStatus').textContent=f?f.name:'No file';}
async function detectProject(){const f=current();if(!f)return;try{const files={};for(const [n,v] of state.files)files[n]=v.content.slice(0,100000);const r=await fetch('/runtime/detect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:f.name,files})});state.detected=await r.json();const d=state.detected;let label=d.framework?`${d.framework} · ${d.language_label}`:d.language_label;if(d.language==='plaintext')label='Unknown language';$('runtimePill').textContent=label;renderContext();}catch{state.detected=null;$('runtimePill').textContent=f.language;}}
function openFile(name,content){const lang=languageFor(name);state.files.set(name,{name,content,original:content,language:lang,dirty:false});state.active=name;$('editorEmpty').classList.add('hidden');renderTabs();renderContext();if(state.editor){state.editor.setValue(content);state.monaco.editor.setModelLanguage(state.editor.getModel(),lang);state.editor.focus();}updateCursor();detectProject();scheduleLive();}
function openMany(files){let pending=files.length;for(const file of files){if(file.size>2*1024*1024)continue;const reader=new FileReader();reader.onload=()=>{openFile(file.webkitRelativePath||file.name,String(reader.result));if(--pending===0)detectProject();};reader.readAsText(file);}}
function updateCursor(){if(!state.editor)return;const p=state.editor.getPosition();$('cursorStatus').textContent=`Ln ${p.lineNumber}, Col ${p.column}`;}
function syncEditor(){const f=current();if(!f||!state.editor)return;const v=state.editor.getValue();if(v!==f.content){f.content=v;f.dirty=v!==f.original;renderTabs();}}
function addHistory(label,detail){state.history.unshift({time:new Date().toLocaleTimeString(),label,detail});if(state.history.length>30)state.history.pop();}
function setBottom(tab){document.querySelectorAll('.panel-tab').forEach(x=>x.classList.toggle('active',x.dataset.bottom===tab));renderBottom(tab);}
function renderBottom(tab='output'){const out=state.lastOutput||{},r=state.aiResult||{};let html='';
 if(tab==='output')html=`<div class="output-head"><span>${out.ok?'✓ Execution successful':out.stderr?'✕ Execution failed':'Ready'}</span><span>${out.duration_ms?out.duration_ms+' ms':''}</span></div><pre class="terminal">${esc(out.stdout||out.stderr||'Run the current file to see live output.')}</pre>`;
 if(tab==='problems'){const issues=r.issues||[];html=issues.length?issues.map(i=>`<div class="problem ${esc(i.severity||'warning')}" data-line="${i.line||1}"><span class="severity">${esc((i.severity||'warning').toUpperCase())}</span><div><b>${esc(i.message||'Issue')}</b><small>${esc(i.type||'')} ${i.line?'· line '+i.line:''}</small></div><button data-ai="fix">Fix</button></div>`).join(''):`<div class="empty-panel"><span>✓</span><b>No reported problems</b><p>Run the code or ask BugFalse AI to analyze the current file.</p></div>`;}
 if(tab==='tests')html=`<div class="empty-panel"><span>✓</span><b>Test runner ready</b><p>Use AI to generate tests, then run them in your project runtime.</p></div>`;
 if(tab==='analysis')html=`<div class="analysis-grid"><div class="score">${r.score??'—'}<small>health score</small></div><div><h3>${esc(r.summary?.errors??0)} errors · ${esc(r.summary?.warnings??0)} warnings</h3><p>${esc(r.analysis||r.explanation||'No analysis yet. Use Analyze, Fix, or Improve.')}</p></div></div>`;
 if(tab==='diff'){if(!r.fixed_code)html='<div class="empty-panel"><span>↔</span><b>No proposed changes</b><p>Ask AI to fix or improve the current file.</p></div>';else html=`<div class="diff-toolbar"><span>AI proposal</span><button class="toolbar-btn small" id="rejectDiff">Reject</button><button class="primary-btn small" id="applyDiff">Apply</button></div><div class="diff-view">${diffHtml(current()?.content||'',r.fixed_code)}</div>`;}
 $('bottomContent').innerHTML=html;$('problemCount').textContent=(r.issues||[]).length||0;if(out.ok)$('outputDot').className='status-dot good';else if(out.stderr)$('outputDot').className='status-dot bad';else $('outputDot').className='status-dot';}
function diffHtml(before,after){const a=before.split('\n'),b=after.split('\n'),max=Math.max(a.length,b.length);let out='';for(let i=0;i<max;i++){if(a[i]===b[i])out+=`<div class="diff-row"><span>${i+1}</span><code>  ${esc(a[i]??'')}</code></div>`;else{if(a[i]!==undefined)out+=`<div class="diff-row removed"><span>${i+1}</span><code>- ${esc(a[i])}</code></div>`;if(b[i]!==undefined)out+=`<div class="diff-row added"><span>${i+1}</span><code>+ ${esc(b[i])}</code></div>`;}}return out;}
function parseTraceLine(s){const m=String(s).match(/(?:line|:)(?:\s*)(\d+)/);return m?Number(m[1]):null;}
async function execute(){syncEditor();const f=current();if(!f){toast('Open a code file first');return;}state.running=true;setStatus('Running…','running');$('runBtn').disabled=true;$('stopBtn').disabled=false;state.lastOutput=null;renderBottom('output');try{const c=new AbortController();state.abort=c;const res=await fetch('/execute/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:f.content,filename:f.name}),signal:c.signal});const data=await res.json();if(!res.ok)throw new Error(data.detail||'Execution failed');state.lastOutput=data;addHistory(data.ok?'Run passed':'Run failed',f.name);setStatus(data.ok?'Verified':data.runtime_available===false?'Runtime unavailable':'Runtime error',data.ok?'ready':'error');renderBottom('output');if(data.stderr){const line=parseTraceLine(data.stderr);if(line&&state.editor){state.editor.revealLineInCenter(line);state.editor.setPosition({lineNumber:line,column:1});}}}catch(e){if(e.name!=='AbortError'){state.lastOutput={ok:false,stderr:e.message};setStatus('Execution failed','error');renderBottom('output');}}finally{state.running=false;$('runBtn').disabled=false;$('stopBtn').disabled=true;}}
function scheduleLive(){clearTimeout(state.timer);if(!$('liveToggle').checked)return;const f=current();if(!f||!['python','javascript','php','ruby','go','rust','c','cpp','java','typescript','swift'].includes(f.language))return;state.timer=setTimeout(execute,state.debounce);}
function formatAiText(text=''){let html=esc(text);html=html.replace(/```([\s\S]*?)```/g,'<pre class="ai-code">$1</pre>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\n- /g,'<br>• ').replace(/\n/g,'<br>');return html;}
function addAiMessage(type,text){const chat=$('aiChat');const welcome=chat.querySelector('.ai-welcome');if(welcome)welcome.remove();const d=document.createElement('div');d.className='chat-msg '+type;d.innerHTML=type==='progress'?`<div class="ai-progress"><span class="pulse"></span><span>${esc(text)}</span></div>`:`<div class="msg-label">${type==='user'?'You':'BugFalse AI'}</div><div class="msg-body">${type==='assistant'?formatAiText(text):esc(text)}</div>`;chat.appendChild(d);chat.scrollTop=chat.scrollHeight;return d;}
async function ai(mode='analyze',prompt=''){syncEditor();const f=current();if(!f){toast('Open a code file first');return;}const request=prompt||({analyze:'Analyze this code',fix:'Find and fix the bugs',improve:'Improve this code while preserving behavior'}[mode]||'Analyze this code');addAiMessage('user',request);const progress=addAiMessage('progress','Analyzing the current code…');setStatus('AI working…','running');try{const res=await fetch('/debug/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:f.content,mode})});const data=await res.json();if(!res.ok)throw new Error(data.detail||'AI request failed');progress.remove();state.aiResult=data;addHistory('AI '+mode,f.name);addAiMessage('assistant',data.analysis||data.explanation||data.summary?.message||'Analysis complete.');if(data.fixed_code&&['fix','improve','refactor','optimize','security'].includes(mode)){setBottom('diff');setStatus('AI proposal ready','ready');}else{setBottom('analysis');setStatus('Analysis complete','ready');}}catch(e){progress.remove();addAiMessage('assistant','I could not complete that request. '+e.message);setStatus('AI failed','error');}}
function applyAI(){const f=current(),r=state.aiResult;if(!f||!r?.fixed_code)return;addHistory('AI changes applied',f.name);f.content=r.fixed_code;f.dirty=true;state.editor.setValue(f.content);renderTabs();renderBottom('diff');detectProject();scheduleLive();addAiMessage('assistant','Changes applied. Validating the updated file now.');}
function rejectAI(){state.aiResult=null;renderBottom('diff');setStatus('Proposal rejected','ready');}
function downloadFile(){const f=current();if(!f){toast('Nothing to download');return;}const blob=new Blob([f.content],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);addHistory('Downloaded file',f.name);}
async function downloadProject(){if(!state.files.size){toast('No project files');return;}const zip=new JSZip();for(const f of state.files.values())zip.file(f.name,f.content);const blob=await zip.generateAsync({type:'blob'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='bugfalse-project.zip';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function toast(msg){let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t);}t.textContent=msg;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),2500);}
function loadMonaco(){require.config({paths:{vs:'https://cdn.jsdelivr.net/npm/monaco-editor@0.52.2/min/vs'}});require(['vs/editor/editor.main'],()=>{state.monaco=monaco;state.editor=monaco.editor.create($('monaco'),{value:'',language:'python',theme:'vs-dark',automaticLayout:true,fontSize:15,lineHeight:23,fontFamily:'JetBrains Mono, SFMono-Regular, Consolas, monospace',minimap:{enabled:true},padding:{top:12,bottom:12},scrollBeyondLastLine:false,roundedSelection:false,renderWhitespace:'selection',smoothScrolling:true});state.editor.onDidChangeModelContent(()=>{syncEditor();updateCursor();scheduleLive();});state.editor.onDidChangeCursorPosition(updateCursor);});}
function openSample(){openFile('main.py',SAMPLE);}
function init(){
 loadMonaco();renderBottom('output');
 $('fileInput').multiple=true;
 $('uploadBtn').onclick=()=>$('fileInput').click();$('emptyUpload').onclick=()=>$('fileInput').click();$('fileInput').onchange=e=>{if(e.target.files.length)openMany([...e.target.files]);e.target.value='';};$('emptySample').onclick=openSample;
 $('runBtn').onclick=execute;$('stopBtn').onclick=()=>state.abort?.abort();$('downloadBtn').onclick=downloadFile;
 document.querySelectorAll('.ai-modes [data-ai]').forEach(b=>b.onclick=()=>ai(b.dataset.ai));
 document.querySelectorAll('.panel-tab').forEach(b=>b.onclick=()=>setBottom(b.dataset.bottom));
 document.querySelectorAll('[data-suggestion]').forEach(b=>b.onclick=()=>{const q=b.dataset.suggestion;$('aiInput').value='';ai('analyze',q);});
 $('sendAi').onclick=()=>{const q=$('aiInput').value.trim();if(!q)return;$('aiInput').value='';let mode=/improv/i.test(q)?'improve':/fix|bug|error/i.test(q)?'fix':'analyze';ai(mode,q);};
 $('aiInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('sendAi').click();}};
 $('closeAiBtn').onclick=()=>{$('.ai-panel')?.classList.add('collapsed');$('reopenAiBtn').classList.remove('hidden');};
 $('reopenAiBtn').onclick=()=>{$('.ai-panel')?.classList.remove('collapsed');$('reopenAiBtn').classList.add('hidden');};
 $('themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';document.body.classList.toggle('light',state.theme==='light');if(state.editor)monaco.editor.setTheme(state.theme==='light'?'vs':'vs-dark');};
 $('settingsBtn').onclick=()=>$('settingsModal').classList.remove('hidden');$('settingsLive').onchange=e=>$('liveToggle').checked=e.target.checked;$('liveToggle').onchange=e=>$('settingsLive').checked=e.target.checked;$('debounceSelect').onchange=e=>state.debounce=Number(e.target.value);$('minimapToggle').onchange=e=>state.editor?.updateOptions({minimap:{enabled:e.target.checked}});
 document.addEventListener('click',e=>{if(e.target.matches('[data-close]'))$(e.target.dataset.close)?.classList.add('hidden');if(e.target.id==='settingsModal')e.target.classList.add('hidden');if(e.target.id==='applyDiff')applyAI();if(e.target.id==='rejectDiff')rejectAI();if(e.target.matches('[data-ai]'))ai(e.target.dataset.ai);});
 $('bottomContent').addEventListener('click',e=>{const p=e.target.closest('[data-line]');if(p&&state.editor){const line=Number(p.dataset.line);state.editor.revealLineInCenter(line);state.editor.setPosition({lineNumber:line,column:1});state.editor.focus();}});
 $('fileTabs').addEventListener('click',e=>{const close=e.target.closest('[data-close-file]');if(close){const n=close.dataset.closeFile;state.files.delete(n);if(state.active===n){const next=[...state.files.keys()][0];if(next){state.active=next;const f=current();state.editor.setValue(f.content);monaco.editor.setModelLanguage(state.editor.getModel(),f.language);}else{state.active=null;$('editorEmpty').classList.remove('hidden');state.editor.setValue('');}}renderTabs();renderContext();detectProject();return;}const tab=e.target.closest('[data-file]');if(tab){state.active=tab.dataset.file;const f=current();state.editor.setValue(f.content);monaco.editor.setModelLanguage(state.editor.getModel(),f.language);renderTabs();renderContext();detectProject();scheduleLive();}});
 window.addEventListener('dragover',e=>e.preventDefault());window.addEventListener('drop',e=>{e.preventDefault();if(e.dataTransfer.files.length)openMany([...e.dataTransfer.files]);});
 document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();execute();}if(e.key==='Escape')document.querySelectorAll('.modal:not(.hidden)').forEach(x=>x.classList.add('hidden'));});
}
init();
